# Generated by Django 5.0.4 on 2024-05-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuserprofile',
            name='age',
            field=models.IntegerField(default=29),
        ),
    ]
