# Generated by Django 5.0.4 on 2024-05-15 09:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0002_alter_category_options_product_seller_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="seller",
            new_name="user",
        ),
    ]
