# Generated by Django 5.0.4 on 2024-05-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "marketplace",
            "0005_product_quantity_alter_product_description_cart_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="condition",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("used", "Used"),
                    ("refurbished", "Refurbished"),
                ],
                default="new",
                max_length=12,
            ),
        ),
    ]
