# Generated by Django 5.0.4 on 2024-05-23 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_alter_comment_created_at'),
        ('user', '0016_alter_subscription_subscribed_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='user.userprofile'),
        ),
    ]
