# Generated by Django 5.0.4 on 2024-04-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_remove_userprofile_follows_album_backgroundimage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="background_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="background_images/"
            ),
        ),
        migrations.DeleteModel(
            name="BackgroundImage",
        ),
    ]
