# Generated by Django 5.0.4 on 2024-05-02 11:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_userprofile_background_image_delete_backgroundimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="album",
        ),
        migrations.DeleteModel(
            name="Album",
        ),
        migrations.DeleteModel(
            name="Photo",
        ),
    ]
