# Generated by Django 5.0.4 on 2024-05-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_remove_photo_album_delete_album_delete_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="background_image",
            field=models.ImageField(
                blank=True,
                default="background_images/dummy_img.jpg",
                null=True,
                upload_to="background_images/",
            ),
        ),
    ]
