# Generated by Django 5.0.4 on 2024-05-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_alter_userprofile_background_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="background_image",
            field=models.ImageField(
                blank=True,
                default="background_images/dummy_background_img.jpg",
                null=True,
                upload_to="background_images/",
            ),
        ),
    ]
