# Generated by Django 5.0.4 on 2024-05-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0010_alter_userprofile_background_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(
                blank=True,
                default="user_images/dummy-profile-picture.png",
                null=True,
                upload_to="user_images/",
            ),
        ),
    ]
