# Generated by Django 5.0.4 on 2024-05-16 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribers',
            name='profile',
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='user.userprofile')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='user.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Subscribed',
        ),
        migrations.DeleteModel(
            name='Subscribers',
        ),
    ]
